// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaintevizmmsbkuoekgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhaW50ZXZpem1tc2JrdW9la2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDQwNTksImV4cCI6MjA2MjE4MDA1OX0.rj3U7DcTk9OHQLWWw10y--WJ9oc8GIg_uSkQeKLrJ5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);